# Generated by Django 5.1 on 2025-03-05 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phonenumber_user_upload_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be between 7 and 15 digits",
                        regex="^\\d{7,15}$",
                    )
                ],
            ),
        ),
    ]
