# Generated by Django 5.1 on 2025-04-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usertype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserType",
            new_name="UserRole",
        ),
    ]
