# Generated by Django 5.1 on 2025-04-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_usertype_userrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
