# Generated by Django 5.1 on 2025-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name="Settings",
            new_name="Setting",
        ),
        migrations.AddField(
            model_name="userrole",
            name="criteria",
            field=models.ManyToManyField(
                related_name="user_roles", to="users.criteria"
            ),
        ),
    ]
