# Generated by Django 5.1 on 2025-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_criteria_rename_settings_setting_userrole_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="criteria_type",
            field=models.CharField(
                choices=[("delete", "Delete"), ("add", "Add"), ("edit", "Edit")],
                default="delete",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
