# Generated by Django 5.1 on 2025-04-26 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_criteria_criteria_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="upload_limit",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(10)]
            ),
        ),
    ]
