# Generated by Django 5.1 on 2025-05-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("hr_tool", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryblock",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr_tool.employee"
            ),
        ),
        migrations.AddField(
            model_name="salaryblockentry",
            name="salary_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.salaryblock"
            ),
        ),
    ]
