# Generated by Django 5.1 on 2025-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=50, null=True)),
                ("parts", models.CharField(blank=True, max_length=50, null=True)),
                ("parts_relation", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
