# Generated by Django 5.1 on 2025-05-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_account_final_account_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit Card", "Credit Card"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        max_length=255,
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_account",
                        to="finance.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.currency",
                    ),
                ),
                (
                    "opposite_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_opposite_account",
                        to="finance.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payment_account",
                        to="finance.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.currency",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finance.loan"
                    ),
                ),
                (
                    "opposite_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payment_opposite_account",
                        to="finance.account",
                    ),
                ),
            ],
        ),
    ]
