# Generated by Django 5.1 on 2025-05-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_exchangeprice_payroll_delete_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeprice",
            name="first_currency",
        ),
        migrations.RemoveField(
            model_name="exchangeprice",
            name="second_currency",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="employee",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="ExchangePrice",
        ),
        migrations.DeleteModel(
            name="Payroll",
        ),
    ]
