# Generated by Django 5.1 on 2025-05-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_remove_expense_date_loan_loanpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="payment_cycle",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                default="Monthly",
                max_length=255,
            ),
        ),
    ]
