# Generated by Django 5.1 on 2025-05-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0005_remove_exchangeprice_first_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=50, null=True)),
                ("parts", models.CharField(blank=True, max_length=50, null=True)),
                ("parts_relation", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "first_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_currency",
                        to="finance.currency",
                    ),
                ),
                (
                    "second_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_currency",
                        to="finance.currency",
                    ),
                ),
            ],
        ),
    ]
