# Generated by Django 5.1 on 2025-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_loan_payment_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmovement',
            name='origin_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='origin_type',
            field=models.CharField(choices=[('راتب', 'Salary'), ('مصروفات', 'Expense'), ('الإيداعات', 'Loan')], default='test', max_length=50),
            preserve_default=False,
        ),
    ]
