# Generated by Django 5.1 on 2025-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_accountmovement_origin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmovement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
