# Generated by Django 5.1 on 2025-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
