# Generated by Django 5.1 on 2025-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeprice",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
