# Generated by Django 5.1 on 2025-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
