# Generated by Django 5.1 on 2025-05-22 17:22

import utility.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.CharField(default=utility.helper.generate_slug, max_length=20),
        ),
    ]
