# Generated by Django 5.1 on 2025-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="permissin_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("user", "User"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
