# Generated by Django 5.1 on 2025-04-19 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_permissin_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
