# Generated by Django 5.1 on 2025-05-23 04:51

import utility.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=models.SlugField(
                default=utility.helper.generate_slug, max_length=100
            ),
        ),
    ]
