# Generated by Django 5.1 on 2025-01-21 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('reason', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('_', '_')], default='_', max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
