# Generated by Django 5.1 on 2025-05-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[("إضافة", "Addition"), ("خصم", "Discount")],
                        max_length=100,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("work_hours", models.FloatField()),
                ("work_day_friday", models.BooleanField(default=False)),
                ("work_day_tuesday", models.BooleanField(default=False)),
                ("work_day_thursday", models.BooleanField(default=False)),
                ("work_day_wednesday", models.BooleanField(default=False)),
                ("work_day_monday", models.BooleanField(default=False)),
                ("work_day_sunday", models.BooleanField(default=False)),
                ("work_day_saturday", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
