# Generated by Django 5.1 on 2025-01-21 13:50

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_tool', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Full-Time', max_length=100)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance')], default='HR', max_length=100)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('state', models.CharField(choices=[('Done', 'Done'), ('Review', 'Review'), ('Initial', 'Initial')], max_length=30)),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='recruiters/images')),
                ('position', models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Initial', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recruitment/resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.employee'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(choices=[('Full Day', '8 Hours'), ('Half Day', '4 Hours')], max_length=40)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='0%', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.skill')),
            ],
        ),
    ]
