# Generated by Django 5.1 on 2025-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("created", models.DateField(auto_now_add=True)),
                ("employees", models.ManyToManyField(to="hr_tool.employee")),
            ],
        ),
    ]
