# Generated by Django 5.1 on 2025-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
    ]
