# Generated by Django 5.1 on 2025-05-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('hr_tool', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to='finance.account'),
        ),
        migrations.AddField(
            model_name='employee',
            name='opposite_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_opposite_account', to='finance.account'),
        ),
    ]
