# Generated by Django 5.1 on 2025-02-01 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0003_hrsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hrsettings",
            name="name",
        ),
        migrations.RemoveField(
            model_name="hrsettings",
            name="value",
        ),
        migrations.AddField(
            model_name="hrsettings",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("dd/mm/yyyy", "Dmy"),
                    ("mm/dd/yyyy", "Mdy"),
                    ("yyyy/mm/dd", "Ymd"),
                ],
                default="dd/mm/yyyy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hrsettings",
            name="days_in_month",
            field=models.IntegerField(
                default=28,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="hrsettings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="hrsettings",
            name="time_format",
            field=models.CharField(
                choices=[("12h", "Twelve Hour"), ("24h", "Twenty Four Hour")],
                default="12h",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="absence",
            name="reason",
            field=models.CharField(
                choices=[("Sick Leave", "Sick Leave"), ("_", "None")],
                default="_",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[("HR", "Hr"), ("Finance", "Finance")],
                default="HR",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("Intern", "Intern"),
                    ("Full-Time", "Full Time"),
                    ("Part-Time", "Part Time"),
                ],
                default="Full-Time",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="hours",
            field=models.CharField(
                choices=[("8 Hours", "Full Day"), ("4 Hours", "Half Day")],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="position",
            field=models.CharField(
                choices=[
                    ("Intern", "Intern"),
                    ("Full-Time", "Full Time"),
                    ("Part-Time", "Part Time"),
                ],
                default="Initial",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workgoal",
            name="progress",
            field=models.CharField(
                choices=[
                    ("0%", "Zero"),
                    ("25%", "Quarter"),
                    ("50%", "Half"),
                    ("75%", "Three Quarters"),
                    ("100%", "Complete"),
                ],
                default="0%",
                max_length=20,
            ),
        ),
    ]
