# Generated by Django 5.1 on 2025-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0004_remove_hrsettings_name_remove_hrsettings_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default="syria", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="social_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                default="Single",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default="2016-01-01"),
            preserve_default=False,
        ),
    ]
