# Generated by Django 5.1 on 2025-05-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0004_hrloan_hrloanpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hrloan",
            old_name="paymeny_cycle",
            new_name="payment_cycle",
        ),
    ]
