# Generated by Django 5.1 on 2025-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0005_employee_address_employee_social_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[("HR", "Hr"), ("Finance", "Finance")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("Intern", "Intern"),
                    ("Full-Time", "Full Time"),
                    ("Part-Time", "Part Time"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
