# Generated by Django 5.1 on 2025-04-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0006_alter_employee_department_alter_employee_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absence",
            name="days",
        ),
        migrations.AddField(
            model_name="holiday",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
