# Generated by Django 5.1 on 2025-04-29 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0009_employee_department_employee_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="base_salary",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EmployeeCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr_tool.employee",
                    ),
                ),
            ],
        ),
    ]
