# Generated by Django 5.1 on 2025-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0010_employee_base_salary_employeecertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="description",
        ),
        migrations.RemoveField(
            model_name="holiday",
            name="end",
        ),
        migrations.RemoveField(
            model_name="position",
            name="description",
        ),
        migrations.AddField(
            model_name="department",
            name="day_hours",
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_friday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_monday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_saturday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_sunday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_thursday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_tuesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="department",
            name="work_day_wednesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="position",
            name="default_salary",
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
