# Generated by Django 5.1 on 2025-04-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0011_remove_department_description_remove_holiday_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="day_hours",
            new_name="work_hours",
        ),
    ]
