# Generated by Django 5.1 on 2025-05-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0012_rename_day_hours_department_work_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=50, null=True)),
                ("parts", models.CharField(blank=True, max_length=50, null=True)),
                ("parts_relation", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position_currency",
                to="hr_tool.currency",
            ),
        ),
        migrations.CreateModel(
            name="ExchangePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "first_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_currency",
                        to="hr_tool.currency",
                    ),
                ),
                (
                    "second_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_currency",
                        to="hr_tool.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaves", models.FloatField()),
                ("base_salary", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr_tool.employee",
                    ),
                ),
            ],
        ),
    ]
