# Generated by Django 5.1 on 2025-05-02 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0013_currency_position_currency_exchangeprice_payroll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="hours",
        ),
        migrations.AddField(
            model_name="holiday",
            name="days",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
