# Generated by Django 5.1 on 2025-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0014_remove_holiday_hours_holiday_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
