# Generated by Django 5.1 on 2025-05-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_initial"),
        ("hr_tool", "0015_holiday_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position_currency",
                to="finance.currency",
            ),
        ),
        migrations.DeleteModel(
            name="ExchangePrice",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
