# Generated by Django 5.1 on 2025-05-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_initial"),
        ("hr_tool", "0016_alter_position_currency_delete_exchangeprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="salary_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
    ]
