# Generated by Django 5.1 on 2025-05-06 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0018_extrawork"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrawork",
            name="value_per_hour",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
