# Generated by Django 5.1 on 2025-05-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0019_extrawork_value_per_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[("ADDITION", "Addition"), ("DISCOUNT", "Discount")],
                        max_length=100,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr_tool.employee",
                    ),
                ),
            ],
        ),
    ]
