# Generated by Django 5.1 on 2025-05-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_salaryblock_salaryblockentry"),
        ("hr_tool", "0020_additiondiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="additiondiscount",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="extrawork",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
    ]
