# Generated by Django 5.1 on 2025-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_tool", "0021_additiondiscount_currency_extrawork_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absence",
            name="reason",
        ),
        migrations.AlterField(
            model_name="additiondiscount",
            name="type",
            field=models.CharField(
                choices=[("إضافة", "Addition"), ("خصم", "Discount")], max_length=100
            ),
        ),
    ]
