# Generated by Django 5.1 on 2025-05-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="MaterialMove",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
        migrations.DeleteModel(
            name="UnitConversion",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
