# Generated by Django 5.1 on 2025-05-20 16:08

import utility.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="form_builder/logo"
                    ),
                ),
                ("title", models.CharField(default="test", max_length=100)),
                ("welcome", models.CharField(default="test", max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=utility.helper.generate_slug, max_length=100
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("1", "Template 1"),
                            ("2", "Template 2"),
                            ("3", "Template 3"),
                        ],
                        default="1",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
