# Generated by Django 5.1 on 2025-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="language",
            field=models.CharField(default="en", max_length=100),
        ),
    ]
