# Generated by Django 5.1 on 2025-04-27 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0002_customform_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customform",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=100,
            ),
        ),
    ]
