# Generated by Django 5.1 on 2025-04-29 17:46

import utility.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0003_customform_created_at_alter_customform_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="slug",
            field=models.SlugField(
                default=utility.helper.generate_slug, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customform",
            name="title",
            field=models.CharField(default="test", max_length=100),
        ),
        migrations.AddField(
            model_name="customform",
            name="welcome",
            field=models.CharField(default="test", max_length=200),
        ),
    ]
