# Generated by Django 5.1 on 2025-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0004_customform_slug_customform_title_customform_welcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="template",
            field=models.CharField(
                choices=[("1", "Template 1"), ("2", "Template 2"), ("3", "Template 3")],
                default="1",
                max_length=100,
            ),
        ),
    ]
