# Generated by Django 5.1 on 2025-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0005_customform_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="form_builder/logo"
            ),
        ),
    ]
